### ISSUE TITLE
#include format no such file or directory

### ISSUE THREAD

**Issue by xiaoriri-cloud** [worawit/blutter#101]
-- Build files have been written to: /home/xiaoriri/code/blutter-main/build/blutter_dartvm3.3.3_android_arm64
[1/22] Building CXX object CMakeFiles/....3_android_arm64.dir/cmake_pch.hxx.gch
FAILED: CMakeFiles/blutter_dartvm3.3.3_android_arm64.dir/cmake_pch.hxx.gch 
/usr/bin/c++ -DDART_COMPRESSED_POINTERS -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DFRIDA_TEMPLATE_DIR=\"/home/xiaoriri/code/blutter-main/scripts\" -DHAS_RECORD_TYPE -DNDEBUG -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -I/usr/include/capstone -isystem /home/xiaoriri/code/blutter-main/packages/include/dartvm3.3.3 -O3 -DNDEBUG -O3 -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++20 -Winvalid-pch -x c++-header -include /home/xiaoriri/code/blutter-main/build/blutter_dartvm3.3.3_android_arm64/CMakeFiles/blutter_dartvm3.3.3_android_arm64.dir/cmake_pch.hxx -MD -MT CMakeFiles/blutter_dartvm3.3.3_android_arm64.dir/cmake_pch.hxx.gch -MF CMakeFiles/blutter_dartvm3.3.3_android_arm64.dir/cmake_pch.hxx.gch.d -o CMakeFiles/blutter_dartvm3.3.3_android_arm64.dir/cmake_pch.hxx.gch -c /home/xiaoriri/code/blutter-main/build/blutter_dartvm3.3.3_android_arm64/CMakeFiles/blutter_dartvm3.3.3_android_arm64.dir/cmake_pch.hxx.cxx
In file included from /home/xiaoriri/code/blutter-main/build/blutter_dartvm3.3.3_android_arm64/CMakeFiles/blutter_dartvm3.3.3_android_arm64.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/xiaoriri/code/blutter-main/blutter/src/pch.h:12:10: fatal error: format: 没有那个文件或目录
   12 | #include <format>
      |          ^~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/xiaoriri/code/blutter-main/blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/home/xiaoriri/code/blutter-main/blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "/home/xiaoriri/code/blutter-main/blutter.py", line 202, in main2
    build_and_run(input)
  File "/home/xiaoriri/code/blutter-main/blutter.py", line 187, in build_and_run
    cmake_blutter(input)
  File "/home/xiaoriri/code/blutter-main/blutter.py", line 145, in cmake_blutter
    subprocess.run([NINJA_CMD], cwd=builddir, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.
root@node1:/home/xiaoriri/code/blutter-main# ^C
root@node1:/home/xiaoriri/code/blutter-main# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.1.0-8ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2,rust --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-IvzKaI/gcc-13-13.1.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-IvzKaI/gcc-13-13.1.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.1.0 (Ubuntu 13.1.0-8ubuntu1~22.04)

**Comment by cryptax** [comment]
this is a gcc-13 issue if I am correct.

**Comment by worawit** [comment]
Use Ubuntu 24.04. It comes with gcc 13.

Using backport gcc might miss some feature or my script cannot detect all features.
