### ISSUE TITLE
blutter_dartvm3.5.2_android_arm64.exe exit status 3221225477

### ISSUE THREAD

**Issue by xlccccc** [worawit/blutter#107]
python .\blutter.py \arm64-v8a\ .\output\
Dart version: 3.5.2, Snapshot: cda356e9bae476c70de33809fd92e009, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode dedup_instructions no-tsan no-msan arm64 android compressed-pointers
Traceback (most recent call last):
  File "blutter\blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "blutter\blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "blutter\blutter.py", line 202, in main2
    build_and_run(input)
  File "blutter\blutter.py", line 191, in build_and_run
    subprocess.run([input.blutter_file, '-i', input.libapp_path, '-o', input.outdir], check=True)
  File "\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['blutter\\bin\\blutter_dartvm3.5.2_android_arm64.exe', '-i', '\\arm64-v8a\\libapp.so', '-o', '.\\output']' returned non-zero exit status 3221225477.

I will run according to the instructions in readme
```
Windows
Install git and python 3
Install latest Visual Studio with "Desktop development with C++" and "C++ CMake tools"
Install required libraries (libcapstone and libicu4c)
python scripts\init_env_win.py
Start "x64 Native Tools Command Prompt"
```

**Comment by bangsugar** [comment]
I have the exact same issue. Have you resolved it?

**Comment by worawit** [comment]
try latest commit.

if it still does not work, please provide me the binary files.

**Comment by bangsugar** [comment]
The issue still exists, could you please help take a look?

![image](https://github.com/user-attachments/assets/bd900d8d-42b1-48bf-8344-a776fa8de081)

[Uploading 3.5.4_lib.zip…]()

**Comment by bangsugar** [comment]
> try latest commit.
> 
> if it still does not work, please provide me the binary files.

The issue still exists, could you please help take a look?

**Comment by AbhiTheModder** [comment]
@bangsugar the library you provided isn't officially compiled
![IMG_20241114_153609_254](https://github.com/user-attachments/assets/f0fe49c0-24ac-45f2-b53f-8f2466f90f25)

According to a user in the reFlutter repository, the hash aligns with Shorebird (https://shorebird.dev/) as referenced here: https://github.com/Impact-I/reFlutter/issues/314.

And currently they haven't made their dart SDK fork public on which blutter works
![Screenshot_2024-11-14-15-36-45-406_com android chrome](https://github.com/user-attachments/assets/b38b8bc6-199d-4b60-86ee-d469aecbc9e9)
ref. https://docs.shorebird.dev/architecture/#dart-langsdk-the-dart-sdk

**Comment by rajada1** [comment]
> [@bangsugar](https://github.com/bangsugar)a biblioteca que você forneceu não foi compilada oficialmente ![IMG_20241114_153609_254](https://github.com/user-attachments/assets/f0fe49c0-24ac-45f2-b53f-8f2466f90f25)
> 
> De acordo com um usuário no repositório reFlutter, o hash se alinha com Shorebird ( https://shorebird.dev/ ), conforme referenciado aqui: [Impact-I/reFlutter#314](https://github.com/Impact-I/reFlutter/issues/314) .
> 
> E atualmente eles não tornaram público o fork do Dart SDK em que o Blutter funciona ref. https://docs.shorebird.dev/architecture/#dart-langsdk-the-dart-sdk ![Screenshot_2024-11-14-15-36-45-406_com android chrome](https://github.com/user-attachments/assets/b38b8bc6-199d-4b60-86ee-d469aecbc9e9)[](https://docs.shorebird.dev/architecture/#dart-langsdk-the-dart-sdk)

What are the options to make it work with shorebird?

**Comment by misterGFTT** [comment]
😂they still keep the forked Dart-SDK private

**Comment by t0kubetsu** [comment]
Exit code `3221225477` is `0xC0000005` in hex — Windows `STATUS_ACCESS_VIOLATION`, a native crash in the blutter C++ executable itself (not a Python error). This is the same crash pattern as #203. To get a proper stack trace, try building in Debug mode from Visual Studio. If you can share the Dart version and the libapp.so, it may help identify the crash site.
