### ISSUE TITLE
HELP : No such file or directory  &&  ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by Abdusin** [worawit/blutter#108]
C:\Users\Abdus\Desktop\flutter_projects\blutter-main>python blutter.py C:\Users\Abdus\...\arm64-v8a out_dir
Dart version: 3.5.1, Snapshot: 80a49c7111088100a233b2ae788e1f48, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode dedup_instructions no-tsan no-msan arm64 android compressed-pointers
CMake Error at C:/Users/Abdus/.mcuxpressotools/cmake-3.28.1-windows-x86_64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: 'C:/Users/Abdus/Desktop/flutter_projects/blutter-main/build/dartvm3.5.1_android_arm64/CMakeFiles/CMakeScratch/TryCompile-54p7hf'

    Run Build Command(s): C:/Users/Abdus/.mcuxpressotools/ninja/ninja.exe -v cmTC_f37c3
    [1/2] C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe  /nologo   -MDd /showIncludes /FoCMakeFiles\cmTC_f37c3.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_f37c3.dir\ /FS -c C:\Users\Abdus\Desktop\flutter_projects\blutter-main\build\dartvm3.5.1_android_arm64\CMakeFiles\CMakeScratch\TryCompile-54p7hf\testCCompiler.c
    [2/2] C:\Windows\system32\cmd.exe /C "cd . && C:\Users\Abdus\.mcuxpressotools\cmake-3.28.1-windows-x86_64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_f37c3.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_f37c3.dir\testCCompiler.c.obj  /out:cmTC_f37c3.exe /implib:cmTC_f37c3.lib /pdb:cmTC_f37c3.pdb /version:0.0 /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    FAILED: cmTC_f37c3.exe
    C:\Windows\system32\cmd.exe /C "cd . && C:\Users\Abdus\.mcuxpressotools\cmake-3.28.1-windows-x86_64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_f37c3.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_f37c3.dir\testCCompiler.c.obj  /out:cmTC_f37c3.exe /implib:cmTC_f37c3.lib /pdb:cmTC_f37c3.pdb /version:0.0 /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_f37c3.dir/manifest.res CMakeFiles\cmTC_f37c3.dir/manifest.rc" failed (exit code 0) with the following output:
    no such file or directory
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "C:\Users\ ...\blutter-main\blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "C:\Users\ ...\blutter-main\blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "C:\Users\ ...\blutter-main\blutter.py", line 202, in main2
    build_and_run(input)
  File "C:\Users\ ...\blutter-main\blutter.py", line 168, in build_and_run
    fetch_and_build(input.dart_info)
  File "C:\Users\ ...\blutter-main\dartvm_fetch_build.py", line 135, in fetch_and_build
    cmake_dart(info, outdir)
  File "C:\Users\ ...\blutter-main\dartvm_fetch_build.py", line 125, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={info.os_name}', f'-DTARGET_ARCH={info.arch}',
    
    
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'C:\\Users\\Abdus\\...\\blutter-main\\build\\dartvm3.5.1_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.

**Comment by t0kubetsu** [comment]
This error means CMake can't find or run the C++ compiler. On Windows you must use the **x64 Native Tools Command Prompt for VS 2022** (found under Start → Visual Studio 2022 → x64 Native Tools Command Prompt). Running from a regular cmd, PowerShell, or Git Bash won't have the MSVC compiler in PATH.
