### ISSUE TITLE
blutter_dartvm3.5.3 error: invalid shift for array operation

### ISSUE THREAD

**Issue by TGxiaobaicai** [worawit/blutter#109]
> 
-- Installing: /root/test/blutter/blutter/../bin/blutter_dartvm3.5.3_android_arm64
libapp is loaded at 0x7fa745c00000
Dart heap at 0x7fa600000000
Analyzing the application
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xa77c60: mov x29, x15
    0xa77c64: and x15, x15, #0xfffffffffffffff0
    0xa77c68: mov x19, sp
    0xa77c6c: mov sp, x15
  * 0xa77c70: str x9, [x26, #0x750]
    0xa77c74: blr x9
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xa77c60: mov x29, x15
    0xa77c64: and x15, x15, #0xfffffffffffffff0
    0xa77c68: mov x19, sp
    0xa77c6c: mov sp, x15
  * 0xa77c70: str x9, [x26, #0x750]
    0xa77c74: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xa77c78: movz x16, #0x8
    0xa77c7c: str x16, [x26, #0x750]
    0xa77c80: mov sp, x19
    0xa77c84: mov x15, x29
  * 0xa77c88: ldr x29, [x15], #8
    0xa77c8c: b #0xa77cac
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xa76e94: mov x29, x15
    0xa76e98: and x15, x15, #0xfffffffffffffff0
    0xa76e9c: mov x19, sp
    0xa76ea0: mov sp, x15
  * 0xa76ea4: str x9, [x26, #0x750]
    0xa76ea8: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xa76eac: movz x16, #0x8
    0xa76eb0: str x16, [x26, #0x750]
    0xa76eb4: mov sp, x19
    0xa76eb8: mov x15, x29
  * 0xa76ebc: ldr x29, [x15], #8
    0xa76ec0: mov x9, x20
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xa7716c: mov x29, x15
    0xa77170: and x15, x15, #0xfffffffffffffff0
    0xa77174: mov x19, sp
    0xa77178: mov sp, x15
  * 0xa7717c: str x9, [x26, #0x750]
    0xa77180: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xa77184: movz x16, #0x8
    0xa77188: str x16, [x26, #0x750]
    0xa7718c: mov sp, x19
    0xa77190: mov x15, x29
  * 0xa77194: ldr x29, [x15], #8
    0xa77198: mov x2, x20
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xa77444: mov x29, x15
    0xa77448: and x15, x15, #0xfffffffffffffff0
    0xa7744c: mov x19, sp
    0xa77450: mov sp, x15
  * 0xa77454: str x9, [x26, #0x750]
    0xa77458: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xa7745c: movz x16, #0x8
    0xa77460: str x16, [x26, #0x750]
    0xa77464: mov sp, x19
    0xa77468: mov x15, x29
  * 0xa7746c: ldr x29, [x15], #8
    0xa77470: mov x2, x23
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xa77730: mov x29, x15
    0xa77734: and x15, x15, #0xfffffffffffffff0
    0xa77738: mov x19, sp
    0xa7773c: mov sp, x15
  * 0xa77740: str x9, [x26, #0x750]
    0xa77744: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xa77748: movz x16, #0x8
    0xa7774c: str x16, [x26, #0x750]
    0xa77750: mov sp, x19
    0xa77754: mov x15, x29
  * 0xa77758: ldr x29, [x15], #8
    0xa7775c: ldur x0, [x29, #-0x58]
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xa778bc: mov x29, x15
    0xa778c0: and x15, x15, #0xfffffffffffffff0
    0xa778c4: mov x19, sp
    0xa778c8: mov sp, x15
  * 0xa778cc: str x9, [x26, #0x750]
    0xa778d0: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xa778d4: movz x16, #0x8
    0xa778d8: str x16, [x26, #0x750]
    0xa778dc: mov sp, x19
    0xa778e0: mov x15, x29
  * 0xa778e4: ldr x29, [x15], #8
    0xa778e8: mov x7, x20
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xaf308c: mov x29, x15
    0xaf3090: and x15, x15, #0xfffffffffffffff0
    0xaf3094: mov x19, sp
    0xaf3098: mov sp, x15
  * 0xaf309c: str x9, [x26, #0x750]
    0xaf30a0: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xaf30a4: movz x16, #0x8
    0xaf30a8: str x16, [x26, #0x750]
    0xaf30ac: mov sp, x19
    0xaf30b0: mov x15, x29
  * 0xaf30b4: ldr x29, [x15], #8
    0xaf30b8: mov x9, x20
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xaf33f0: mov x29, x15
    0xaf33f4: and x15, x15, #0xfffffffffffffff0
    0xaf33f8: mov x19, sp
    0xaf33fc: mov sp, x15
  * 0xaf3400: str x9, [x26, #0x750]
    0xaf3404: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xaf3408: movz x16, #0x8
    0xaf340c: str x16, [x26, #0x750]
    0xaf3410: mov sp, x19
    0xaf3414: mov x15, x29
  * 0xaf3418: ldr x29, [x15], #8
    0xaf341c: ldur x8, [x29, #-0x48]
Analysis error at line 645 `std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)`: insn.id() == ARM64_INS_BLR
    0xaf3700: mov x29, x15
    0xaf3704: and x15, x15, #0xfffffffffffffff0
    0xaf3708: mov x19, sp
    0xaf370c: mov sp, x15
  * 0xaf3710: str x9, [x26, #0x750]
    0xaf3714: blr x9
Analysis error at line 448 `std::unique_ptr<LeaveFrameInstr> FunctionAnalyzer::processLeaveFrameInstr(AsmIterator&)`: insn.id() == ARM64_INS_LDP && insn.op_count() == 4
    0xaf3718: movz x16, #0x8
    0xaf371c: str x16, [x26, #0x750]
    0xaf3720: mov sp, x19
    0xaf3724: mov x15, x29
  * 0xaf3728: ldr x29, [x15], #8
    0xaf372c: mov x7, x20
Analysis error at line 2850 `std::unique_ptr<AllocateObjectInstr> FunctionAnalyzer::processTryAllocateObject(AsmIterator&)`: inst_size == 0x10
    0xa6c910: ldur x1, [x29, #-0x38]
    0xa6c914: add x16, x3, x1, lsl #4
    0xa6c918: ldr q0, [x16]
    0xa6c91c: ldp x3, x4, [x26, #0x50]
  * 0xa6c920: add x3, x3, #0x20
    0xa6c924: cmp x4, x3
/root/test/blutter/blutter/src/CodeAnalyzer_arm64.cpp: 3175: error: invalid shift for array operation
Traceback (most recent call last):
  File "/root/test/blutter/../blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/root/test/blutter/../blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "/root/test/blutter/../blutter.py", line 202, in main2
    build_and_run(input)
  File "/root/test/blutter/../blutter.py", line 191, in build_and_run
    subprocess.run([input.blutter_file, '-i', input.libapp_path, '-o', input.outdir], check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/test/blutter/bin/blutter_dartvm3.5.3_android_arm64', '-i', '/root/test/blutter/so/libapp.so', '-o', 'out/']' died with <Signals.SIGABRT: 6>.
>

**Comment by worawit** [comment]
Can you provide me binary files?

**Comment by TGxiaobaicai** [comment]
> Can you provide me binary files?

Using the latest commit, the previous error didn't occur, but the following error appeared:DartDumper.cpp: 652: error: Unhandle internal class _Int32x4 (64)
[Uploading 3.5.3_lib.zip…]()

**Comment by worawit** [comment]
> > Can you provide me binary files?
> 
> Using the latest commit, the previous error didn't occur, but the following error appeared:DartDumper.cpp: 652: error: Unhandle internal class _Int32x4 (64) [3.5.3_lib.zip](https://github.com/user-attachments/files/17728796/3.5.3_lib.zip)

Should work now in latest commit
