### ISSUE TITLE
FileNotFoundError: subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={info.os_name}', f'-DTARGET_ARCH={info.arch}'

### ISSUE THREAD

**Issue by hopemycode2n4pole** [worawit/blutter#111]
I follow guide 
`https://github.com/ZJ595/AndroidReverse/blob/main/Article/%E7%95%AA%E5%A4%96%E5%AE%9E%E6%88%98%E7%AF%873-%E6%8B%A8%E4%BA%91%E8%A7%81%E6%97%A5%E4%B9%8B%E6%B5%85%E8%B0%88Flutter%E9%80%86%E5%90%91.md`
do something, first it works good,
```
C:\Users\rlblk\Downloads\RayLink_8.3.1_anti>python blutter.py .\arm64-v8a\ .\output
Dart version: 3.2.3, Snapshot: f71c76320d35b65f1164dbaa6d95fe09, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-tsan no-asserts arm64 android compressed-pointers null-safety
Cloning into 'C:\Users\rlblk\Downloads\RayLink_8.3.1_anti\dartsdk\v3.2.3'...
remote: Enumerating objects: 2588, done.
remote: Counting objects: 100% (2588/2588), done.
remote: Compressing objects: 100% (2100/2100), done.
remote: Total 2588 (delta 85), reused 1526 (delta 57), pack-reused 0 (from 0)
Receiving objects: 100% (2588/2588), 1.53 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (85/85), done.
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 24 (delta 0), reused 8 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (24/24), 134.82 KiB | 979.00 KiB/s, done.
Updating files: 100% (24/24), done.
remote: Enumerating objects: 3639, done.
remote: Counting objects: 100% (3639/3639), done.
remote: Compressing objects: 100% (2648/2648), done.
remote: Total 3639 (delta 1172), reused 1910 (delta 948), pack-reused 0 (from 0)
Receiving objects: 100% (3639/3639), 8.82 MiB | 2.51 MiB/s, done.
Resolving deltas: 100% (1172/1172), done.
Updating files: 100% (4120/4120), done.
```
but finally it error
```
Traceback (most recent call last):
  File "C:\Users\rlblk\Downloads\RayLink_8.3.1_anti\blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "C:\Users\rlblk\Downloads\RayLink_8.3.1_anti\blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "C:\Users\rlblk\Downloads\RayLink_8.3.1_anti\blutter.py", line 202, in main2
    build_and_run(input)
  File "C:\Users\rlblk\Downloads\RayLink_8.3.1_anti\blutter.py", line 168, in build_and_run
    fetch_and_build(input.dart_info)
  File "C:\Users\rlblk\Downloads\RayLink_8.3.1_anti\dartvm_fetch_build.py", line 135, in fetch_and_build
    cmake_dart(info, outdir)
  File "C:\Users\rlblk\Downloads\RayLink_8.3.1_anti\dartvm_fetch_build.py", line 125, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={info.os_name}', f'-DTARGET_ARCH={info.arch}',
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rlblk\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rlblk\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rlblk\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```
How could I solve this problem?

**Comment by worawit** [comment]
cmake is not found.

install cmake in VS setup tool and using VS command prompt

**Comment by FlutterGenerator** [comment]
Hi brother, I'm waiting for a response fix to armeabi-v7a
