### ISSUE TITLE
FAILED: CMakeFiles/blutter_dartvm2.19.6_android_arm64.dir/src/DartTypes.cpp.obj

### ISSUE THREAD

**Issue by rickbrian** [worawit/blutter#117]
[4/22] Building CXX object CMakeFiles\blutter_dartvm2.19.6_android_arm64.dir\src\DartTypes.cpp.obj
FAILED: CMakeFiles/blutter_dartvm2.19.6_android_arm64.dir/src/DartTypes.cpp.obj
"D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe"  /nologo /TP -DDART_COMPRESSED_POINTERS -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DFRIDA_TEMPLATE_DIR=\"D:/Logan/apks/baac/arm64-v8a/blutter/scripts\" -DHAS_TYPE_REF -DNDEBUG -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -external:I D:\Logan\apks\baac\arm64-v8a\blutter\packages\include\dartvm2.19.6 -external:I D:\Logan\apks\baac\arm64-v8a\blutter\blutter\..\external\capstone\include\capstone -external:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -MD /Oy /GR- /sdl- /Oi /GL /Gy /Zc:wchar_t /Zc:inline -std:c++20 /YuD:/Logan/apks/baac/arm64-v8a/blutter/build/blutter_dartvm2.19.6_android_arm64/CMakeFiles/blutter_dartvm2.19.6_android_arm64.dir/cmake_pch.hxx /FpD:/Logan/apks/baac/arm64-v8a/blutter/build/blutter_dartvm2.19.6_android_arm64/CMakeFiles/blutter_dartvm2.19.6_android_arm64.dir/./cmake_pch.cxx.pch /FID:/Logan/apks/baac/arm64-v8a/blutter/build/blutter_dartvm2.19.6_android_arm64/CMakeFiles/blutter_dartvm2.19.6_android_arm64.dir/cmake_pch.hxx /showIncludes /FoCMakeFiles\blutter_dartvm2.19.6_android_arm64.dir\src\DartTypes.cpp.obj /FdCMakeFiles\blutter_dartvm2.19.6_android_arm64.dir\ /FS -c D:\Logan\apks\baac\arm64-v8a\blutter\blutter\src\DartTypes.cpp
D:\Logan\apks\baac\arm64-v8a\blutter\blutter\src\DartTypes.cpp(237): error C2039: "parameterized_function_type": 不是 "dart::TypeParameter" 的成员
D:\Logan\apks\baac\arm64-v8a\blutter\packages\include\dartvm2.19.6\vm/object.h(9264): note: 参见“dart::TypeParameter”的声明
D:\Logan\apks\baac\arm64-v8a\blutter\blutter\src\DartTypes.cpp(237): error C2530: “owner”: 必须初始化引用
D:\Logan\apks\baac\arm64-v8a\blutter\blutter\src\DartTypes.cpp(238): error C3536: “owner”: 初始化之前无法使用
D:\Logan\apks\baac\arm64-v8a\blutter\blutter\src\DartTypes.cpp(238): error C2530: “type_parameters”: 必须初始化引用
D:\Logan\apks\baac\arm64-v8a\blutter\blutter\src\DartTypes.cpp(239): error C3536: “type_parameters”: 初始化之前无法使用
[17/22] Building CXX object CMakeFiles\blutter_dartvm2.19.6_android_arm64.dir\src\DartDumper.cpp.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Logan\apks\baac\arm64-v8a\blutter\blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "D:\Logan\apks\baac\arm64-v8a\blutter\blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "D:\Logan\apks\baac\arm64-v8a\blutter\blutter.py", line 202, in main2
    build_and_run(input)
  File "D:\Logan\apks\baac\arm64-v8a\blutter\blutter.py", line 187, in build_and_run
    cmake_blutter(input)
  File "D:\Logan\apks\baac\arm64-v8a\blutter\blutter.py", line 145, in cmake_blutter
    subprocess.run([NINJA_CMD], cwd=builddir, check=True)
  File "C:\Users\PC\.pyenv\pyenv-win\versions\3.11.4\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.

How to solve this problem

**Comment by MasterShi** [comment]
Rollback to previous version: https://codeload.github.com/worawit/blutter/zip/45c7302dfba1f0b291e298637695897e19276007, this works for me

**Comment by worawit** [comment]
fixed in latest commit

**Comment by t0kubetsu** [comment]
Dart 2.x is not supported. Blutter requires Dart 3.x AOT binaries. The snapshot format and register ABI changed significantly between Dart 2 and Dart 3.
