### ISSUE TITLE
dartvm3.5.4 error: invalid shift for array operation

### ISSUE THREAD

**Issue by zhong820290** [worawit/blutter#119]
Dart version: 3.5.4, Snapshot: 80a49c7111088100a233b2ae788e1f48, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode dedup_instructions no-tsan no-msan arm64 android compressed-pointers
libapp is loaded at 0x7f749bcf2000
Dart heap at 0x7f7300000000
Analyzing the application
Analysis error at line 2915 `std::unique_ptr<AllocateObjectInstr> FunctionAnalyzer::processTryAllocateObject(AsmIterator&)`: inst_size == 0x10
    0xaae530: ldur x1, [x29, #-0x38]
    0xaae534: add x16, x3, x1, lsl #4
    0xaae538: ldr q0, [x16]
    0xaae53c: ldp x3, x4, [x26, #0x50]
  * 0xaae540: add x3, x3, #0x20
    0xaae544: cmp x4, x3
/root/blutter/blutter/src/CodeAnalyzer_arm64.cpp: 3241: error: invalid shift for array operation
Traceback (most recent call last):
  File "/root/blutter/blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/root/blutter/blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "/root/blutter/blutter.py", line 202, in main2
    build_and_run(input)
  File "/root/blutter/blutter.py", line 191, in build_and_run
    subprocess.run([input.blutter_file, '-i', input.libapp_path, '-o', input.outdir], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/blutter/bin/blutter_dartvm3.5.4_android_arm64', '-i', '/root/arm64-v8a/libapp.so', '-o', './out_dir']' died with <Signals.SIGABRT: 6>.

[dartvm3.5.4.zip](https://github.com/user-attachments/files/17895465/dartvm3.5.4.zip)

**Comment by t0kubetsu** [comment]
This is an analysis assertion failure specific to Dart 3.5.4. If you still see this on the latest `main` branch, please share the snapshot hash shown in the blutter output — some assertion failures are version-specific and can be investigated if a reproducible case is provided.
