### ISSUE TITLE
What is this problem? 'ninja'？？

### ISSUE THREAD

**Issue by xiaogui824** [worawit/blutter#121]
CMake Warning (dev) at CMakeLists.txt:111 (install):
  Policy CMP0177 is not set: install() DESTINATION paths are normalized.  Run
  "cmake --help-policy CMP0177" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (1.6s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/blutter/build/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis
[1/22] Building CXX ob....dir/cmake_pch.hxx.pc
FAILED: CMakeFiles/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis.dir/cmake_pch.hxx.pch
/data/data/com.termux/files/usr/bin/c++ -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DFRIDA_TEMPLATE_DIR=\"/data/data/com.termux/files/home/blutter/scripts\" -DHAS_SHARED_CLASS_TABLE -DHAS_TYPE_REF -DNDEBUG -DNO_CODE_ANALYSIS -DNO_INIT_LATE_STATIC_FIELD -DNO_LAST_INTERNAL_ONLY_CID -DNO_METHOD_EXTRACTOR_STUB -DOLD_MAP_NO_IMMUTABLE -DOLD_MAP_SET_NAME -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -isystem /data/data/com.termux/files/home/blutter/packages/include/dartvm2.7.0 -O3 -DNDEBUG -std=c++20 -fexperimental-library -O3 -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -Winvalid-pch -fpch-instantiate-templates -Xclang -emit-pch -Xclang -include -Xclang /data/data/com.termux/files/home/blutter/build/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis/CMakeFiles/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis.dir/cmake_pch.hxx -x c++-header -MD -MT CMakeFiles/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis.dir/cmake_pch.hxx.pch -MF CMakeFiles/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis.dir/cmake_pch.hxx.pch.d -o CMakeFiles/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis.dir/cmake_pch.hxx.pch -c /data/data/com.termux/files/home/blutter/build/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis/CMakeFiles/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis.dir/cmake_pch.hxx.cxx
In file included from <built-in>:1:
In file included from /data/data/com.termux/files/home/blutter/build/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis/CMakeFiles/blutter_dartvm2.7.0_android_arm64_no-compressed-ptrs_no-analysis.dir/cmake_pch.hxx:5:
/data/data/com.termux/files/home/blutter/blutter/src/pch.h:35:10: fatal error: 'vm/tagged_pointer.h' file not found
   35 | #include <vm/tagged_pointer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 202, in main2
    build_and_run(input)
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 187, in build_and_run
    cmake_blutter(input)
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 145, in cmake_blutter
    subprocess.run([NINJA_CMD], cwd=builddir, check=True)
  File "/data/data/com.termux/files/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.

**Comment by xiaogui824** [comment]
> Dart 2.7 太旧了。不支持。

能不能更新支持呢？这软件对我很重要的

**Comment by xiaogui824** [comment]
> Dart 2.7 is too old. No support.

Can you update and support this version?Thank you

**Comment by skabdulhaq** [comment]
Same issue did you find any fix

**Comment by t0kubetsu** [comment]
The ninja error itself is a side effect of the real issue: Dart 2.7 is not supported. Blutter requires Dart 3.x. For the user reporting Dart 3.5.0 with snapshot hash `80a49c7111088100a233b2ae788e1f48` — please share the full ninja error output (not just the CMake warning) so the actual build failure can be diagnosed. The CMake warning about `CMP0177` is harmless and not the root cause.
