### ISSUE TITLE
blutter.py script throws CalledProcessError exception during subprocess.run execution

### ISSUE THREAD

**Issue by JJBJJ** [worawit/blutter#123]
-- Build files have been written to: D:/desktop/pystudio/blutter/build/blutter_dartvm3.5.3_android_arm64
[22/22] Linking CXX executable blutter_dartvm3.5.3_android_arm64.exe
-- Install configuration: "Release"
-- Installing: D:/desktop/pystudio/blutter/blutter/../bin/blutter_dartvm3.5.3_android_arm64.exe
Traceback (most recent call last):
  File "D:\desktop\pystudio\blutter\blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "D:\desktop\pystudio\blutter\blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "D:\desktop\pystudio\blutter\blutter.py", line 202, in main2
    build_and_run(input)
  File "D:\desktop\pystudio\blutter\blutter.py", line 191, in build_and_run
    subprocess.run([input.blutter_file, '-i', input.libapp_path, '-o', input.outdir], check=True)
  File "D:\anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\desktop\\pystudio\\blutter\\bin\\blutter_dartvm3.5.3_android_arm64.exe', '-i',

**Comment by JJBJJ** [comment]
Build process succeeded but blutter_dartvm3.5.3_android_arm64.exe execution failed

**Comment by t0kubetsu** [comment]
The build succeeded but the blutter executable itself crashed at runtime. This is the same pattern as #203 and #107: the Python `CalledProcessError` is just reporting that the subprocess exited with a non-zero code. On Linux/macOS this is usually a `SIGSEGV`; on Windows it's `0xC0000005` (ACCESS_VIOLATION). Please share the Dart version and snapshot hash from the output lines before the crash, and update to the latest `main` branch first (recent fixes address several crash sites).
