### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_symbol_by_name'

### ISSUE THREAD

**Issue by WesleyRhodes** [worawit/blutter#14]
https://drive.google.com/file/d/1dOKkEERFIsHPlKL8xpf5183ojLutkDMl/view?usp=drive_link
```
Traceback (most recent call last):
  File "D:\Android\blutter\blutter\blutter.py", line 138, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "D:\Android\blutter\blutter\blutter.py", line 84, in main
    dart_version, snapshot_hash, arch, os_name = extract_dart_info(libapp_file, libflutter_file)
  File "D:\Android\blutter\blutter\extract_dart_info.py", line 104, in extract_dart_info
    snapshot_hash = extract_snapshot_hash(libapp_file)
  File "D:\Android\blutter\blutter\extract_dart_info.py", line 20, in extract_snapshot_hash
    sym = dynsym.get_symbol_by_name('_kDartVmSnapshotData')[0]
AttributeError: 'NoneType' object has no attribute 'get_symbol_by_name'
```

**Comment by lemon-lengleng** [comment]
我遇到了同样的问题，请问您是怎么解决的？

**Comment by chain00x** [comment]
same problem

**Comment by t0kubetsu** [comment]
This error means `elf.get_section_by_name('.dynsym')` returned `None` — the ELF file has no `.dynsym` (dynamic symbol table) section. This can happen if:
1. The libapp.so is stripped or packed
2. You pointed blutter at the wrong file (e.g., the APK itself instead of the extracted .so)
3. The .so is 32-bit (blutter only supports arm64)

Verify with: `readelf -S libapp.so | grep dynsym` — if there is no `.dynsym` section, the file is not a standard Flutter libapp.so.
