### ISSUE TITLE
CMake Error: The source directory "/root/blutter/dartsdk/v3.2.0/--log-level=NOTICE" does not exist.

### ISSUE THREAD

**Issue by CHINA-china** [worawit/blutter#25]
`root@VM-12-6-ubuntu:~/blutter# python3 blutter.py /root/arm64-v8a/ /root/AA/
Dart version: 3.2.0, Snapshot: f71c76320d35b65f1164dbaa6d95fe09, Target: android arm64
CMake Error: The source directory "/root/blutter/dartsdk/v3.2.0/--log-level=NOTICE" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "blutter.py", line 138, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "blutter.py", line 101, in main
    fetch_and_build(dart_version, arch, os_name)
  File "/root/blutter/dartvm_fetch_build.py", line 110, in fetch_and_build
    cmake_dart(ver, arch, os_name, outdir)
  File "/root/blutter/dartvm_fetch_build.py", line 102, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE'], cwd=target_dir, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', '/root/blutter/build/dartvm3.2.0_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
`
gcc verison
`
root@VM-12-6-ubuntu:~/blutter# gcc --version
gcc (Ubuntu 13.1.0-8ubuntu1~18.04) 13.1.0
`

**Comment by CHINA-china** [comment]
**The above issue has been resolved, but new issues have emerged。**

Dart version: 3.2.0, Snapshot: f71c76320d35b65f1164dbaa6d95fe09, Target: android arm64
-- Found the following ICU libraries:
--   uc (required)
-- Release
-- Configuring done
-- Generating done
-- Build files have been written to: /root/blutter/build/dartvm3.2.0_android_arm64
[2/196] Building CXX object CMakeFiles/dartvm3.2.0_android_arm64.dir/runtime/vm/regexp_parser.cc.o
FAILED: CMakeFiles/dartvm3.2.0_android_arm64.dir/runtime/vm/regexp_parser.cc.o 
/usr/bin/c++ -DDART_COMPRESSED_POINTERS -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DNDEBUG -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -I/root/blutter/dartsdk/v3.2.0/runtime -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1z -MD -MT CMakeFiles/dartvm3.2.0_android_arm64.dir/runtime/vm/regexp_parser.cc.o -MF CMakeFiles/dartvm3.2.0_android_arm64.dir/runtime/vm/regexp_parser.cc.o.d -o CMakeFiles/dartvm3.2.0_android_arm64.dir/runtime/vm/regexp_parser.cc.o -c /root/blutter/dartsdk/v3.2.0/runtime/vm/regexp_parser.cc
/root/blutter/dartsdk/v3.2.0/runtime/vm/regexp_parser.cc: In function ‘bool dart::{anonymous}::IsSupportedBinaryProperty(UProperty)’:
/root/blutter/dartsdk/v3.2.0/runtime/vm/regexp_parser.cc:1592:10: error: ‘UCHAR_EXTENDED_PICTOGRAPHIC’ was not declared in this scope
 1592 |     case UCHAR_EXTENDED_PICTOGRAPHIC:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[4/196] Building CXX object CMakeFiles/dartvm3.2.0_android_arm64.dir/runtime/vm/json_writer.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "blutter.py", line 138, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "blutter.py", line 101, in main
    fetch_and_build(dart_version, arch, os_name)
  File "/root/blutter/dartvm_fetch_build.py", line 110, in fetch_and_build
    cmake_dart(ver, arch, os_name, outdir)
  File "/root/blutter/dartvm_fetch_build.py", line 105, in cmake_dart
    subprocess.run([NINJA_CMD], cwd=builddir, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.
![image](https://github.com/worawit/blutter/assets/92798047/3b7b1af6-a33f-4a6d-a72f-81f4e9737ffd)
![image](https://github.com/worawit/blutter/assets/92798047/9f11157c-7bbd-49fd-97df-13e4ee86a3f9)

**Comment by t0kubetsu** [comment]
As the maintainer noted, the `libicu` on Ubuntu 18.04 is too old. This requires ICU 63+ which is available on Ubuntu 23.10+, Debian Trixie+, or any distro with libicu-dev >= 63. On older systems, consider using a Docker container with a newer distro.
