### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by OYyunshen** [worawit/blutter#26]
OS:kali
g++:gcc version 13.2.0 (Debian 13.2.0-5) 
clang:Debian clang version 16.0.6 (16)
I uesd this tool,but it can't run,show elf file section error,may elf file can't identify.

Traceback (most recent call last):
  File "/root/blutter/blutter.py", line 138, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "/root/blutter/blutter.py", line 84, in main
    dart_version, snapshot_hash, arch, os_name = extract_dart_info(libapp_file, libflutter_file)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/blutter/extract_dart_info.py", line 104, in extract_dart_info
    snapshot_hash = extract_snapshot_hash(libapp_file)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/blutter/extract_dart_info.py", line 19, in extract_snapshot_hash
    dynsym = elf.get_section_by_name('.dynsym')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/elftools/elf/elffile.py", line 151, in get_section_by_name
    self._make_section_name_map()
  File "/usr/lib/python3/dist-packages/elftools/elf/elffile.py", line 679, in _make_section_name_map
    for i, sec in enumerate(self.iter_sections()):
  File "/usr/lib/python3/dist-packages/elftools/elf/elffile.py", line 174, in iter_sections
    section = self.get_section(i)
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/elftools/elf/elffile.py", line 141, in get_section
    return self._make_section(section_header)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/elftools/elf/elffile.py", line 645, in _make_section
    return self._make_symbol_table_section(section_header, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/elftools/elf/elffile.py", line 687, in _make_symbol_table_section
    return SymbolTableSection(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/elftools/elf/sections.py", line 174, in __init__
    elf_assert(self['sh_entsize'] > 0,
  File "/usr/lib/python3/dist-packages/elftools/common/utils.py", line 80, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/usr/lib/python3/dist-packages/elftools/common/utils.py", line 143, in _assert_with_exception
    raise exception_type(msg)
elftools.common.exceptions.ELFError: Expected entry size of section '' to be > 0

**Comment by worawit** [comment]
May be it is a corrupted ELF file. You can try using "objdump" or "readelf" command for checking your libapp.so.

**Comment by OYyunshen** [comment]
Thank you for your reply. I have checked this so file and indeed found some errors. I have no further questions

**Comment by t0kubetsu** [comment]
This error from `pyelftools` means the `.dynsym` section header has an invalid `sh_entsize` of 0, which typically indicates a corrupted ELF file. As the maintainer suggested, verify with `readelf -S libapp.so` — if the section sizes look wrong, the file may have been corrupted during extraction from the APK.
