### ISSUE TITLE
can not find file

### ISSUE THREAD

**Issue by Dyingchen** [worawit/blutter#33]
Dart version: 3.0.2, Snapshot: aa64af18e7d086041ac127cc4bc50c5e, Target: android arm64
flags: product no-code_comments dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety
Traceback (most recent call last):
  File ".\blutter.py", line 168, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File ".\blutter.py", line 130, in main
    fetch_and_build(dart_version, arch, os_name, has_compressed_ptrs, snapshot_hash)
  File "E:\Git\blutter\dartvm_fetch_build.py", line 118, in fetch_and_build
    outdir = checkout_dart(ver, snapshot_hash)
  File "E:\Git\blutter\dartvm_fetch_build.py", line 49, in checkout_dart
    subprocess.run([GIT_CMD, '-c', 'advice.detachedHead=false', 'clone', '-b', ver, '--depth', '1', '--filter=blob:none', '--sparse', '--progress', DART_GIT_URL, clonedir], check=True)
  File "E:\python\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by yzctzl** [comment]
you need install [git](https://git-scm.com/download/win) and put git in your path

**Comment by Dyingchen** [comment]
> you need install [git](https://git-scm.com/download/win) and put git in your path

tks 

The git I am using is portable, which is why this issue occurred
