### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by autumn-moon-py** [worawit/blutter#45]
why?

cmd log
```
Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
  File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
  File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
    cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
  File "D:\project\blutter\blutter.py", line 169, in main
    fetch_and_build(
  File "D:\project\blutter\blutter.py", line 250, in <module>
    main(input, outdir, rebuild, vs_sln, no_analysis)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
```

**Comment by AbhiTheModder** [comment]
> why?
> 
> cmd log
> 
> ```
> Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
>   File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
>     subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
>   File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
>     cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
>   File "D:\project\blutter\blutter.py", line 169, in main
>     fetch_and_build(
>   File "D:\project\blutter\blutter.py", line 250, in <module>
>     main(input, outdir, rebuild, vs_sln, no_analysis)
> subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> ```

It'll be better to share the logs above this too, this is just exit logs not where the issue occurred

**Comment by autumn-moon-py** [comment]
> > why? 为什么？
> > cmd log CMD 日志
> > ```
> > Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> >   File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
> >     subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
> >   File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
> >     cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
> >   File "D:\project\blutter\blutter.py", line 169, in main
> >     fetch_and_build(
> >   File "D:\project\blutter\blutter.py", line 250, in <module>
> >     main(input, outdir, rebuild, vs_sln, no_analysis)
> > subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> > ```
> 
> It'll be better to share the logs above this too, this is just exit logs not where the issue occurred最好也分享上面的日志，这只是退出日志，而不是问题发生的地方

```
(venv) D:\project\blutter>python blutter.py
Dart version: 3.0.5, Snapshot: 90b56a561f70cd55e972cb49b79b3d8b, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety
CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY
  _ICU_REQUIRED_LIBS_FOUND)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindICU.cmake:334 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "D:\project\blutter\blutter.py", line 250, in <module>
    main(input, outdir, rebuild, vs_sln, no_analysis)
  File "D:\project\blutter\blutter.py", line 169, in main
    fetch_and_build(
  File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
    cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
  File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
  File "D:\develop\miniconda\envs\py310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
```

**Comment by dedshit** [comment]
> > > why? 为什么？
> > > cmd log CMD 日志
> > > ```
> > > Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> > >   File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
> > >     subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
> > >   File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
> > >     cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
> > >   File "D:\project\blutter\blutter.py", line 169, in main
> > >     fetch_and_build(
> > >   File "D:\project\blutter\blutter.py", line 250, in <module>
> > >     main(input, outdir, rebuild, vs_sln, no_analysis)
> > > subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> > > ```
> > 
> > 
> > It'll be better to share the logs above this too, this is just exit logs not where the issue occurred最好也分享上面的日志，这只是退出日志，而不是问题发生的地方
> 
> ```
> (venv) D:\project\blutter>python blutter.py
> Dart version: 3.0.5, Snapshot: 90b56a561f70cd55e972cb49b79b3d8b, Target: android arm64
> flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety
> CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY
>   _ICU_REQUIRED_LIBS_FOUND)
> Call Stack (most recent call first):
>   C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   C:/Program Files/CMake/share/cmake-3.29/Modules/FindICU.cmake:334 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:20 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> Traceback (most recent call last):
>   File "D:\project\blutter\blutter.py", line 250, in <module>
>     main(input, outdir, rebuild, vs_sln, no_analysis)
>   File "D:\project\blutter\blutter.py", line 169, in main
>     fetch_and_build(
>   File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
>     cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
>   File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
>     subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
>   File "D:\develop\miniconda\envs\py310\lib\subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> ```

run init_env_win.py

**Comment by autumn-moon-py** [comment]
> > > > 为什么？为什么？ cmd log cmd 日志
> > > > ```
> > > > Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> > > >   File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
> > > >     subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
> > > >   File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
> > > >     cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
> > > >   File "D:\project\blutter\blutter.py", line 169, in main
> > > >     fetch_and_build(
> > > >   File "D:\project\blutter\blutter.py", line 250, in <module>
> > > >     main(input, outdir, rebuild, vs_sln, no_analysis)
> > > > subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> > > > ```
> > > 
> > > 
> > > 最好也分享上面的日志，这只是退出日志，而不是问题发生的地方最好也分享上面的日志，这只是退出日志，而不是问题发生的地方
> > 
> > 
> > ```
> > (venv) D:\project\blutter>python blutter.py
> > Dart version: 3.0.5, Snapshot: 90b56a561f70cd55e972cb49b79b3d8b, Target: android arm64
> > flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety
> > CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
> >   Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY
> >   _ICU_REQUIRED_LIBS_FOUND)
> > Call Stack (most recent call first):
> >   C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
> >   C:/Program Files/CMake/share/cmake-3.29/Modules/FindICU.cmake:334 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
> >   CMakeLists.txt:20 (find_package)
> > 
> > 
> > -- Configuring incomplete, errors occurred!
> > Traceback (most recent call last):
> >   File "D:\project\blutter\blutter.py", line 250, in <module>
> >     main(input, outdir, rebuild, vs_sln, no_analysis)
> >   File "D:\project\blutter\blutter.py", line 169, in main
> >     fetch_and_build(
> >   File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
> >     cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
> >   File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
> >     subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
> >   File "D:\develop\miniconda\envs\py310\lib\subprocess.py", line 526, in run
> >     raise CalledProcessError(retcode, process.args,
> > subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> > ```
> 
> 运行init_env_win.py

I have already performed this step

```
(venv) D:\project\blutter\scripts>python init_env_win.py
Downloading ICU library from https://github.com/unicode-org/icu/releases/download/release-73-2/icu4c-73_2-Win64-MSVC2019.zip
Extracting ICU library
Downloading Capstone from https://github.com/capstone-engine/capstone/releases/download/4.0.2/capstone-4.0.2-win64.zip
Extracting Capstone library
Copying dlls to bin directory
Done

(venv) D:\project\blutter>python blutter.py
Dart version: 3.0.5, Snapshot: 90b56a561f70cd55e972cb49b79b3d8b, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety
CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY
  _ICU_REQUIRED_LIBS_FOUND)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindICU.cmake:334 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "D:\project\blutter\blutter.py", line 250, in <module>
    main(input, outdir, rebuild, vs_sln, no_analysis)
  File "D:\project\blutter\blutter.py", line 169, in main
    fetch_and_build(
  File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
    cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
  File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
  File "D:\develop\miniconda\envs\py310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
```

**Comment by autumn-moon-py** [comment]
> no virtual env
> 
> ```
> D:\project\blutter>python -V
> Python 3.11.4
> 
> D:\project\blutter>python blutter.py
> Dart version: 3.0.5, Snapshot: 90b56a561f70cd55e972cb49b79b3d8b, Target: android arm64
> flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety
> CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY
>   _ICU_REQUIRED_LIBS_FOUND)
> Call Stack (most recent call first):
>   C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   C:/Program Files/CMake/share/cmake-3.29/Modules/FindICU.cmake:334 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:20 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> Traceback (most recent call last):
>   File "D:\project\blutter\blutter.py", line 250, in <module>
>     main(input, outdir, rebuild, vs_sln, no_analysis)
>   File "D:\project\blutter\blutter.py", line 169, in main
>     fetch_and_build(
>   File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
>     cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
>   File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
>     subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\develop\miniconda\Lib\subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
> ```

other
```
C:\Users\Administrator\Desktop>cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.


C:\Users\Administrator\Desktop>ninja
ninja: error: loading 'build.ninja': 系统找不到指定的文件。
```

**Comment by dedshit** [comment]
@autumn-moon-py now run init_env_win.py

**Comment by worawit** [comment]
If you run init_env_win.py after first fail, the wrong ICU path might be cached by CMake. Deleting "build" folder and try again.

**Comment by autumn-moon-py** [comment]
> If you run init_env_win.py after first fail, the wrong ICU path might be cached by CMake. Deleting "build" folder and try again.

it can not solve this error

**Comment by worawit** [comment]
Did you delete "build" folder before running the command again?

**Comment by autumn-moon-py** [comment]
> Did you delete "build" folder before running the command again?

yes，i try it

**Comment by worawit** [comment]
I have no idea now. You can try new clone of this project and start over again.

Make sure "external/icu-windows/include/unicode/*.h" and "external/lib64/icu*.lib" existed before running blutter.py

**Comment by timwai** [comment]
Intsall "Windows 11 SDK"

**Comment by t0kubetsu** [comment]
On Windows, the ICU and Capstone libraries must be downloaded first. Run:
```
python scripts\init_env_win.py
```
Then delete the `build\` folder and retry. Also make sure you are using the **x64 Native Tools Command Prompt for VS 2022** (not a regular cmd/PowerShell) when running cmake/ninja.
