### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by Oicite** [worawit/blutter#56]
(pytest38) PS C:\Users\1232\Desktop\blutter> python blutter.py arm64-v8a ./output
Dart version: 3.1.0, Snapshot: 7dbbeeb8ef7b91338640dca3927636de, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety
Cloning into 'C:\Users\1232\Desktop\blutter\dartsdk\v3.1.0'...
remote: Enumerating objects: 2487, done.
remote: Counting objects: 100% (2487/2487), done.
remote: Compressing objects: 100% (2040/2040), done.
remote: Total 2487 (delta 76), reused 1430 (delta 49), pack-reused 0
Receiving objects: 100% (2487/2487), 1.49 MiB | 3.16 MiB/s, done.
Resolving deltas: 100% (76/76), done.
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 24 (delta 0), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (24/24), 130.09 KiB | 594.00 KiB/s, done.
Updating files: 100% (24/24), done.
remote: Enumerating objects: 3590, done.
remote: Counting objects: 100% (3590/3590), done.
remote: Compressing objects: 100% (2578/2578), done.
remote: Total 3590 (delta 1176), reused 1924 (delta 968), pack-reused 0
Receiving objects: 100% (3590/3590), 8.21 MiB | 5.20 MiB/s, done.
Resolving deltas: 100% (1176/1176), done.
Updating files: 100% (4070/4070), done.
Traceback (most recent call last):
  File "blutter.py", line 168, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "blutter.py", line 130, in main
    fetch_and_build(dart_version, arch, os_name, has_compressed_ptrs, snapshot_hash)
  File "C:\Users\1232\Desktop\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
    cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
  File "C:\Users\1232\Desktop\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
  File "E:\anaconda\envs\pytest38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\anaconda\envs\pytest38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\anaconda\envs\pytest38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by worawit** [comment]
Install Visual Studio and using its command prompt "x64 Native Tools Command Prompt".

https://github.com/worawit/blutter#windows

**Comment by t0kubetsu** [comment]
CMake is included with Visual Studio 2022 but is only available in the **x64 Native Tools Command Prompt for VS 2022** environment. Regular cmd, PowerShell, or Git Bash don't have it in PATH. Open Start → Visual Studio 2022 → x64 Native Tools Command Prompt for VS 2022 and run blutter from there.
