### ISSUE TITLE
FAILED: CMakeFiles/dartvm3.1.5_android_arm64.dir/runtime/vm/code_observers.cc.obj

### ISSUE THREAD

**Issue by its4win** [worawit/blutter#62]
Hi, I've got this error when execute the script.

I ran the script on Windows and already run

> python scripts\init_env_win.py

but I still got this error: (for complete on error_log.txt) 
[error_log.txt](https://github.com/worawit/blutter/files/15144530/error_log.txt)

May someone help to give the solution ? Thanks.

-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: T:/blutter/build/dartvm3.1.5_android_arm64
[1/255] Building CXX object CMakeFiles/dartvm3.1.5_android_arm64.dir/runtime/vm/code_observers.cc.obj
FAILED: CMakeFiles/dartvm3.1.5_android_arm64.dir/runtime/vm/code_observers.cc.obj 
V:\mingw64\bin\c++.exe -DDART_COMPRESSED_POINTERS -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DNDEBUG -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -IT:/blutter/dartsdk/v3.1.5/runtime -IT:/icu-windows/include -O3 -DNDEBUG -std=gnu++17 -fvisibility=hidden -fno-keep-inline-dllexport -O3 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MD -MT CMakeFiles/dartvm3.1.5_android_arm64.dir/runtime/vm/code_observers.cc.obj -MF CMakeFiles\dartvm3.1.5_android_arm64.dir\runtime\vm\code_observers.cc.obj.d -o CMakeFiles/dartvm3.1.5_android_arm64.dir/runtime/vm/code_observers.cc.obj -c T:/blutter/dartsdk/v3.1.5/runtime/vm/code_observers.cc
In file included from T:/blutter/dartsdk/v3.1.5/runtime/vm/os_thread.h:27,
                 from T:/blutter/dartsdk/v3.1.5/runtime/vm/code_observers.cc:8:
T:/blutter/dartsdk/v3.1.5/runtime/vm/os_thread_win.h:98:10: error: 'Mutex' does not name a type
   98 |   static Mutex* mutex_;
...
...
...
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "T:\blutter\blutter.py", line 168, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "T:\blutter\blutter.py", line 130, in main
    fetch_and_build(dart_version, arch, os_name, has_compressed_ptrs, snapshot_hash)
  File "T:\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
    cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
  File "T:\blutter\dartvm_fetch_build.py", line 115, in cmake_dart
    subprocess.run([NINJA_CMD], cwd=builddir, check=True)
  File "C:\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.

**Comment by yzctzl** [comment]
don't use c++ compiler from mingw64, try "x64 Native Tools Command Prompt" from Visual Studio.
https://github.com/worawit/blutter/#windows

**Comment by t0kubetsu** [comment]
As confirmed in the comments, this is caused by using MinGW64 instead of MSVC. Blutter on Windows requires Visual Studio 2022 and must be built from the **x64 Native Tools Command Prompt for VS 2022**. MinGW/MSYS2 are not supported.
