### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Wendale** [worawit/blutter#65]
Traceback (most recent call last):
  File "/Users/mojun/Documents/QianXun/project/9club/FlutterProject/flutter_old_base/Blutter/blutter/blutter.py", line 168, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/Users/mojun/Documents/QianXun/project/9club/FlutterProject/flutter_old_base/Blutter/blutter/blutter.py", line 99, in main
    from extract_dart_info import extract_dart_info
  File "/Users/mojun/Documents/QianXun/project/9club/FlutterProject/flutter_old_base/Blutter/blutter/extract_dart_info.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Wendale** [comment]
Traceback (most recent call last):
  File "/Users/mojun/Documents/QianXun/project/9club/FlutterProject/flutter_old_base/Blutter/blutter/blutter.py", line 168, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/Users/mojun/Documents/QianXun/project/9club/FlutterProject/flutter_old_base/Blutter/blutter/blutter.py", line 99, in main
    from extract_dart_info import extract_dart_info
  File "/Users/mojun/Documents/QianXun/project/9club/FlutterProject/flutter_old_base/Blutter/blutter/extract_dart_info.py", line 10, in <module>
    from elftools.elf.elffile import ELFFile
ModuleNotFoundError: No module named 'elftools'
