### ISSUE TITLE
make_version.py exception 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jinxiaoshu** [worawit/blutter#7]
![image](https://github.com/worawit/blutter/assets/49808116/581e8c8e-79cf-4b99-a93c-5419611e53bd)
大佬，这个该如何解决
Boss, how can we solve this

**Comment by worawit** [comment]
An error occurs in Dart make_version.py. I've never found this error.
Can you give me what Dart version is getting compiled.

**Comment by jinxiaoshu** [comment]
![image](https://github.com/worawit/blutter/assets/49808116/d2b4efe3-7945-4bb9-a5fb-e490db9349f8)
this?

**Comment by jinxiaoshu** [comment]
I just gave it a try and it is indeed a problem with Dart version. Dart version: 2.19.6 is acceptable

**Comment by worawit** [comment]
Version 2.10.4 is too old for this project. I have no plan to support it.

From the error, I think it requires python 2.7 to run the script in Dart SDK project.
Even if you could build the SDK, I guess the blutter would not be compiled or run correctly.

**Comment by xiejiale123** [comment]
Dart version: 2.18.6, My mistake is the same as the one above. Is 2.18.6 unacceptable?

**Comment by 2651899617** [comment]
I also reported an error and used Python 2.7 to report invalid syntax

**Comment by 2651899617** [comment]
D:\Tools\blutter\blutter-main>python blutter.py ./arm64-v8a/ ./output
Dart version: 3.1.2, Snapshot: 7dbbeeb8ef7b91338640dca3927636de, Target: android arm64
Cloning into 'D:\Tools\blutter\blutter-main\dartsdk\v3.1.2'...
remote: Enumerating objects: 2487, done.
remote: Counting objects: 100% (2487/2487), done.
remote: Compressing objects: 100% (2028/2028), done.
Receiving objects: 100% (2487/2487), 1.49 MiB | 5.36 MiB/s, done.d 0Receiving objects:  99% (2463/2487)

Resolving deltas: 100% (81/81), done.
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (23/23), done.
Receiving objects: 100% (24/24), 130.41 KiB | 642.00 KiB/s, done.iving objects:  87% (21/24)

Updating files: 100% (24/24), done.
remote: Enumerating objects: 3587, done.
remote: Counting objects: 100% (3587/3587), done.
remote: Compressing objects: 100% (2542/2542), done.
remote: Total 3587 (delta 1196), reused 1924 (delta 1002), pack-reused 0Receiving objects: 100% (3587/3587), 7.45 MiB | Receiving objects: 100% (3587/3587), 8.20 MiB | 924.00 KiB/s, done.

Resolving deltas: 100% (1196/1196), done.
Updating files: 100% (4067/4067), done.
make_version.py exception
'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "blutter.py", line 138, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "blutter.py", line 101, in main
    fetch_and_build(dart_version, arch, os_name)
  File "D:\Tools\blutter\blutter-main\dartvm_fetch_build.py", line 109, in fetch_and_build
    outdir = checkout_dart(ver)
  File "D:\Tools\blutter\blutter-main\dartvm_fetch_build.py", line 76, in checkout_dart
    subprocess.run([sys.executable, 'tools/make_version.py', '--output', 'runtime/vm/version.cc', '--input', 'runtime/vm/version_in.cc'], cwd=clonedir, check=True)
  File "C:\Users\2651899617\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\2651899617\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', 'tools/make_version.py', '--output', 'runtime/vm/version.cc', '--input', 'runtime/vm/version_in.cc']' returned non-zero exit status 4294967295.

**Comment by uuyjp** [comment]
I have solevd it by using other python which version is 3.11.

**Comment by Onekki** [comment]
I have the same issue with dart version 2.10.5

**Comment by Prince-cool** [comment]
meet same issue,how can i do for it?
![image](https://github.com/worawit/blutter/assets/62496012/388d10b3-bc59-49f1-8cf0-c2de4d4b2552)

**Comment by QAQQL** [comment]
你可以修改以下代码
You can modify the following code

./blutter/dartsdk/v2.10.5/make_version.py
`version = version.replace('{{COMMIT_TIME}}', version_time.decode('utf-8'))`
改为
change to
`version = version.replace('{{COMMIT_TIME}}', version_time)`

并根据报错的command手动执行一次编译
And manually execute a compilation according to the command that reported an error
```
 File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'tools/make_version.py', '--output', 'runtime/vm/version.cc', '--input', 'runtime/vm/version_in.cc']' returned non-zero exit status 255.
```

例: 
sample:
```
cd dartsdk/v2.10.5/
/usr/bin/python3 tools/make_version.py --output runtime/vm/version.cc --input runtime/vm/version_in.cc
```
继续执行你刚才的pyhton即可
and rerun your py command
`python3 blutter.py  ./arm64-v8a ./out`

**Comment by Prince-cool** [comment]
> 你可以修改以下代码 You can modify the following code
> 
> ./blutter/dartsdk/v2.10.5/make_version.py `version = version.replace('{{COMMIT_TIME}}', version_time.decode('utf-8'))` 改为 change to `version = version.replace('{{COMMIT_TIME}}', version_time)`
> 
> 并根据报错的command手动执行一次编译 And manually execute a compilation according to the command that reported an error
> 
> ```
>  File "/usr/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/usr/bin/python3', 'tools/make_version.py', '--output', 'runtime/vm/version.cc', '--input', 'runtime/vm/version_in.cc']' returned non-zero exit status 255.
> ```
> 
> 例: sample:
> 
> ```
> cd dartsdk/v2.10.5/
> /usr/bin/python3 tools/make_version.py --output runtime/vm/version.cc --input runtime/vm/version_in.cc
> ```
> 
> 继续执行你刚才的pyhton即可 and rerun your py command `python3 blutter.py ./arm64-v8a ./out`

my Dart version: 3.1.5, Snapshot: 7dbbeeb8ef7b91338640dca3927636de, Target: android arm64
![image](https://github.com/worawit/blutter/assets/62496012/9cb7fc3d-f97d-448d-a1ae-ed0a4e2bee8b)
it‘s replace right，but it wrong too

**Comment by QAQQL** [comment]
请粘贴你报错的行数和提示
Please paste the number of lines you reported incorrectly and the prompt

**Comment by QAQQL** [comment]
> > 你可以修改以下代码 You can modify the following code
> > ./blutter/dartsdk/v2.10.5/make_version.py `version = version.replace('{{COMMIT_TIME}}', version_time.decode('utf-8'))` 改为 change to `version = version.replace('{{COMMIT_TIME}}', version_time)`
> > 并根据报错的command手动执行一次编译 And manually execute a compilation according to the command that reported an error
> > ```
> >  File "/usr/lib/python3.11/subprocess.py", line 571, in run
> >     raise CalledProcessError(retcode, process.args,
> > subprocess.CalledProcessError: Command '['/usr/bin/python3', 'tools/make_version.py', '--output', 'runtime/vm/version.cc', '--input', 'runtime/vm/version_in.cc']' returned non-zero exit status 255.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 例: sample:
> > ```
> > cd dartsdk/v2.10.5/
> > /usr/bin/python3 tools/make_version.py --output runtime/vm/version.cc --input runtime/vm/version_in.cc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 继续执行你刚才的pyhton即可 and rerun your py command `python3 blutter.py ./arm64-v8a ./out`
> 
> my Dart version: 3.1.5, Snapshot: 7dbbeeb8ef7b91338640dca3927636de, Target: android arm64 ![image](https://private-user-images.githubusercontent.com/62496012/295969439-9cb7fc3d-f97d-448d-a1ae-ed0a4e2bee8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTAzOTQsIm5iZiI6MTcwNDk5MDA5NCwicGF0aCI6Ii82MjQ5NjAxMi8yOTU5Njk0MzktOWNiN2ZjM2QtZjk3ZC00NDhkLWExYWUtZWQwYTRlMmJlZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE2MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNWRlMmRhMjg0OWRjZmU4OTY5MjZlNjc4MDQyZjk3OWQ5ZGM1NWVjMjQ3YjkxMTIyY2FlZTg3YmI4ZmE4MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-NzLqKn0r7hkPM-3QGrPI8bIV6CdoVbbV4kk1oQdS0) it‘s replace right，but it wrong too

请粘贴你报错的行数和提示
Please paste the number of lines you reported incorrectly and the prompt

**Comment by Prince-cool** [comment]
> > > 你可以修改以下代码 You can modify the following code
> > > ./blutter/dartsdk/v2.10.5/make_version.py `version = version.replace('{{COMMIT_TIME}}', version_time.decode('utf-8'))` 改为 change to `version = version.replace('{{COMMIT_TIME}}', version_time)`
> > > 并根据报错的command手动执行一次编译 And manually execute a compilation according to the command that reported an error
> > > ```
> > >  File "/usr/lib/python3.11/subprocess.py", line 571, in run
> > >     raise CalledProcessError(retcode, process.args,
> > > subprocess.CalledProcessError: Command '['/usr/bin/python3', 'tools/make_version.py', '--output', 'runtime/vm/version.cc', '--input', 'runtime/vm/version_in.cc']' returned non-zero exit status 255.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 例: sample:
> > > ```
> > > cd dartsdk/v2.10.5/
> > > /usr/bin/python3 tools/make_version.py --output runtime/vm/version.cc --input runtime/vm/version_in.cc
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 继续执行你刚才的pyhton即可 and rerun your py command `python3 blutter.py ./arm64-v8a ./out`
> > 
> > 
> > my Dart version: 3.1.5, Snapshot: 7dbbeeb8ef7b91338640dca3927636de, Target: android arm64 ![image](https://private-user-images.githubusercontent.com/62496012/295969439-9cb7fc3d-f97d-448d-a1ae-ed0a4e2bee8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTAzOTQsIm5iZiI6MTcwNDk5MDA5NCwicGF0aCI6Ii82MjQ5NjAxMi8yOTU5Njk0MzktOWNiN2ZjM2QtZjk3ZC00NDhkLWExYWUtZWQwYTRlMmJlZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE2MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNWRlMmRhMjg0OWRjZmU4OTY5MjZlNjc4MDQyZjk3OWQ5ZGM1NWVjMjQ3YjkxMTIyY2FlZTg3YmI4ZmE4MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-NzLqKn0r7hkPM-3QGrPI8bIV6CdoVbbV4kk1oQdS0) it‘s replace right，but it wrong too
> 
> 请粘贴你报错的行数和提示 Please paste the number of lines you reported incorrectly and the prompt

![image](https://github.com/worawit/blutter/assets/62496012/84665765-7e66-4fe7-9842-efafc076ac06)

**Comment by QAQQL** [comment]
> > > > 你可以修改以下代码 You can modify the following code
> > > > ./blutter/dartsdk/v2.10.5/make_version.py `version = version.replace('{{COMMIT_TIME}}', version_time.decode('utf-8'))` 改为 change to `version = version.replace('{{COMMIT_TIME}}', version_time)`
> > > > 并根据报错的command手动执行一次编译 And manually execute a compilation according to the command that reported an error
> > > > ```
> > > >  File "/usr/lib/python3.11/subprocess.py", line 571, in run
> > > >     raise CalledProcessError(retcode, process.args,
> > > > subprocess.CalledProcessError: Command '['/usr/bin/python3', 'tools/make_version.py', '--output', 'runtime/vm/version.cc', '--input', 'runtime/vm/version_in.cc']' returned non-zero exit status 255.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 例: sample:
> > > > ```
> > > > cd dartsdk/v2.10.5/
> > > > /usr/bin/python3 tools/make_version.py --output runtime/vm/version.cc --input runtime/vm/version_in.cc
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 继续执行你刚才的pyhton即可 and rerun your py command `python3 blutter.py ./arm64-v8a ./out`
> > > 
> > > 
> > > my Dart version: 3.1.5, Snapshot: 7dbbeeb8ef7b91338640dca3927636de, Target: android arm64 ![image](https://private-user-images.githubusercontent.com/62496012/295969439-9cb7fc3d-f97d-448d-a1ae-ed0a4e2bee8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTAzOTQsIm5iZiI6MTcwNDk5MDA5NCwicGF0aCI6Ii82MjQ5NjAxMi8yOTU5Njk0MzktOWNiN2ZjM2QtZjk3ZC00NDhkLWExYWUtZWQwYTRlMmJlZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE2MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNWRlMmRhMjg0OWRjZmU4OTY5MjZlNjc4MDQyZjk3OWQ5ZGM1NWVjMjQ3YjkxMTIyY2FlZTg3YmI4ZmE4MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-NzLqKn0r7hkPM-3QGrPI8bIV6CdoVbbV4kk1oQdS0) it‘s replace right，but it wrong too
> > 
> > 请粘贴你报错的行数和提示 Please paste the number of lines you reported incorrectly and the prompt
> 
> ![image](https://github.com/worawit/blutter/assets/62496012/84665765-7e66-4fe7-9842-efafc076ac06)
> 

你修改后是否执行了以下代码？
Did you execute the following code after modification？
'''
cd ./dartsdk/v3.1.5
D:\\Program Files\\python39\\python.exe tools/make_version. py --output runtime/vm/version. cc --input runtime/vm/version_in. cc
'''

参数请根据你的错误提示修改，目录请根据你实际目录修改。
Parameters Please modify according to your error prompt, directory Please modify according to your actual directory.

**Comment by t0kubetsu** [comment]
This error occurs when trying to build with Dart 2.x. Dart 2.x is not supported — blutter requires Dart 3.x AOT binaries. If you are on Dart 3.x and still seeing this, ensure you're using Python 3.9+ (not 3.12+ where some string/bytes semantics changed) and that you're on the latest `main` branch.
