### ISSUE TITLE
error in reflutter apk

### ISSUE THREAD

**Issue by ouyanglong721** [worawit/blutter#70]
I used reflutter to reverse engineer the APK and generated an APK. Then I used blutter to continue to reverse engineer the APK, but an error occurred。

➜  blutter git:(main) python3 blutter.py ../../so/arm64-v8a ../out
Traceback (most recent call last):
  File "/root/project/reverse/utils/blutter/blutter.py", line 168, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/root/project/reverse/utils/blutter/blutter.py", line 100, in main
    dart_version, snapshot_hash, flags, arch, os_name = extract_dart_info(libapp_file, libflutter_file)
  File "/root/project/reverse/utils/blutter/extract_dart_info.py", line 120, in extract_dart_info
    commit_id, dart_version = get_dart_commit(sdk_url)
  File "/root/project/reverse/utils/blutter/extract_dart_info.py", line 80, in get_dart_commit
    with requests.get(url, headers={"Range": "bytes=0-4096"}, stream=True) as r:
  File "/usr/local/python3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/python3/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

**Comment by worawit** [comment]
Why don't you use original libflutter.so with Blutter?

reflutter build their own libflutter.so, so it is obvious that the script cannot find flutter version from official release archive.

**Comment by ouyanglong721** [comment]
> Why don't you use original libflutter.so with Blutter?
> 
> reflutter build their own libflutter.so, so it is obvious that the script cannot find flutter version from official release archive.

Of course i can use original, and i also do it,but i think it’s a better way to help me to analyze flutter app by blutter and reflutter ,because i can use blutter to hook and use reflutter to anaylyse http requests.

**Comment by worawit** [comment]
Blutter only uses libflutter.so for getting Dart version. All output is from libapp.so only.
