### ISSUE TITLE
无法初始化稀疏检出

### ISSUE THREAD

**Issue by July-98** [worawit/blutter#81]
kjy@kjy-VirtualBox:~/github/blutter$ python3 blutter.py /home/kjy/tmp/arm64-v8a out_dir
Dart version: 3.3.2, Snapshot: ee1eb666c76a5cb7746faf39d0b97547, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-tsan no-asserts arm64 android compressed-pointers null-safety
正克隆到 '/home/kjy/github/blutter/dartsdk/v3.3.2'...
fatal: cannot change to 'https://github.com/dart-lang/sdk.git': 没有那个文件或目录
error: 无法初始化稀疏检出
Traceback (most recent call last):
  File "blutter.py", line 175, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "blutter.py", line 137, in main
    fetch_and_build(dart_version, arch, os_name, has_compressed_ptrs, snapshot_hash)
  File "/home/kjy/github/blutter/dartvm_fetch_build.py", line 119, in fetch_and_build
    outdir = checkout_dart(ver, snapshot_hash)
  File "/home/kjy/github/blutter/dartvm_fetch_build.py", line 49, in checkout_dart
    subprocess.run([GIT_CMD, '-c', 'advice.detachedHead=false', 'clone', '-b', ver, '--depth', '1', '--filter=blob:none', '--sparse', '--progress', DART_GIT_URL, clonedir], check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '-c', 'advice.detachedHead=false', 'clone', '-b', '3.3.2', '--depth', '1', '--filter=blob:none', '--sparse', '--progress', 'https://github.com/dart-lang/sdk.git', '/home/kjy/github/blutter/dartsdk/v3.3.2']' returned non-zero exit status 1.

i don'n know how to slove this problem?

**Comment by yzctzl** [comment]
upgrade git to latest version may helps

**Comment by July-98** [comment]
> upgrade git to latest version may helps

thank you

**Comment by t0kubetsu** [comment]
As the contributor noted, this is a Git version issue. The `git sparse-checkout` command requires Git 2.25+. Upgrade git: on Debian/Ubuntu run `sudo apt install git` (or use the git-core PPA for a newer version). Check your version with `git --version`.
