### ISSUE TITLE
Facing a issue to building file in out_dir (empty)

### ISSUE THREAD

**Issue by superman6462** [worawit/blutter#92]
Hell sir, 
I'm facing a issue like this-

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/blutter-termux/blutter.py", line 393, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/data/data/com.termux/files/home/blutter-termux/blutter.py", line 312, in main
    main2(
  File "/data/data/com.termux/files/home/blutter-termux/blutter.py", line 288, in main2
    build_and_run(input)
  File "/data/data/com.termux/files/home/blutter-termux/blutter.py", line 254, in build_and_run
    subprocess.run(
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/data/data/com.termux/files/home/blutter-termux/bin/blutter_dartvm3.2.3_android_arm64', '-i', '/storage/emulated/0/Mod/arm64-v8a/libapp.so', '-o', '/storage/emulated/0/Mod/blutter_out']' died with <Signals.SIGSEGV: 11>.

Please fix it
![Screenshot_2024-08-08-08-19-12-30_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/4d8b7dfe-21f2-4260-9b4c-f9dfdc96e2ce)

**Comment by AbhiTheModder** [comment]
1. What is your snapshot hash for the related dart version?
2. Have you tested with different libs of same dart version do you face similar `segfault` if not then it seems to be similar to #83

**Comment by t0kubetsu** [comment]
SIGSEGV on Termux is often related to the snapshot hash — if your app's libapp.so was not built with the official Flutter SDK (custom engine, Shorebird, etc.), blutter will crash when it can't parse the snapshot. Check the snapshot hash in the blutter output against the official Flutter release list. Also ensure you're on the latest `main` branch, as multiple crash fixes have been merged.
