### ISSUE TITLE
quesiotn details please see it sometime

### ISSUE THREAD

**Issue by 123456789zws** [worawit/blutter#97]
Traceback (most recent call last):
  File "G:\下载3\Downloads\blutter-main\blutter.py", line 175, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "G:\下载3\Downloads\blutter-main\blutter.py", line 137, in main
    fetch_and_build(dart_version, arch, os_name, has_compressed_ptrs, snapshot_h
ash)
  File "G:\下载3\Downloads\blutter-main\dartvm_fetch_build.py", line 119, in fet
ch_and_build
    outdir = checkout_dart(ver, snapshot_hash)
  File "G:\下载3\Downloads\blutter-main\dartvm_fetch_build.py", line 49, in chec
kout_dart
    subprocess.run([GIT_CMD, '-c', 'advice.detachedHead=false', 'clone', '-b', v
er, '--depth', '1', '--filter=blob:none', '--sparse', '--progress', DART_GIT_URL
, clonedir], check=True)
  File "D:\Anaconda3\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>

**Comment by YuHuanTin** [comment]
no 'git' ?, download and install it first
